# Generated by Django 4.2.16 on 2024-10-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('events', '0006_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='authapp.firebaseuser'),
            preserve_default=False,
        ),
    ]
