# Generated by Django 4.2.16 on 2024-10-03 18:46

import authapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('events', '0007_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=authapp.models.FirebaseUser, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='authapp.firebaseuser'),
        ),
    ]
