# Generated by Django 4.2.16 on 2024-10-03 20:04

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('events', '0014_remove_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=events.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='authapp.firebaseuser'),
        ),
    ]
