# Generated by Django 4.2.16 on 2024-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_firebaseuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseuser',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
