# Generated by Django 4.2.16 on 2024-10-04 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_firebaseuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='provider_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
