# Generated by Django 4.2.16 on 2024-09-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_category_alter_project_contributors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(related_name='projects', to='projects.tag'),
        ),
    ]
