# Generated by Django 4.2.16 on 2024-09-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_tag_project_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
