# Generated by Django 4.2.16 on 2024-10-03 20:04

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('projects', '0007_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=projects.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='authapp.firebaseuser'),
        ),
    ]
